name: omniguard
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy
      - pillow
      - torch
      - torchvision
      - gradio>=3.50,<4
      - opencv-python
      - albumentations
      - timm
      - diffusers
      - scipy
      - scikit-image
